# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bridge}
  s.version = "0.0.19"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Kuźma"]
  s.date = %q{2010-03-17}
  s.description = %q{Useful contract bridge utilities - deal generator, id to deal and deal to id conversion}
  s.email = %q{qoobaa+github@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bridge.gemspec",
     "lib/bridge.rb",
     "lib/bridge/bid.rb",
     "lib/bridge/card.rb",
     "lib/bridge/deal.rb",
     "lib/bridge/score.rb",
     "lib/bridge/trick.rb",
     "test/helper.rb",
     "test/test_bid.rb",
     "test/test_bridge.rb",
     "test/test_card.rb",
     "test/test_deal.rb",
     "test/test_score.rb",
     "test/test_trick.rb"
  ]
  s.homepage = %q{http://github.com/qoobaa/bridge}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Contract bridge utilities}
  s.test_files = [
    "test/helper.rb",
     "test/test_bid.rb",
     "test/test_card.rb",
     "test/test_trick.rb",
     "test/test_deal.rb",
     "test/test_bridge.rb",
     "test/test_score.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<test-unit>, [">= 2"])
    else
      s.add_dependency(%q<test-unit>, [">= 2"])
    end
  else
    s.add_dependency(%q<test-unit>, [">= 2"])
  end
end

